version: '3.1'

services:

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wwwroot/nginx.conf:/etc/nginx/nginx.conf
      - ./wwwroot/ssl:/etc/nginx/ssl
    networks:
      - mynetwork

  wp:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 0iN3PE44DY
      WORDPRESS_DB_NAME: wpDB
    volumes:
      - ./server:/var/www/html
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wpDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: 0iN3PE44DY
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  wordpress:
  db:

networks:
  mynetwork: