version: '3.1'

services:
  wp:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 0iN3PE44DY
      WORDPRESS_DB_NAME: wpDB
    volumes:
      - ./server:/var/www/html

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: wpDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: 0iN3PE44DY
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mariadb

volumes:
  wordpress:
  db: